import React from 'react';
import { Alert, Pressable, Share, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { Screen, Eyebrow, PageTitle } from '@/components/Screen';
import { QrPreview } from '@/components/QrPreview';
import { useApp } from '@/context/AppContext';
import { encodeProfile } from '@/lib/encoding';
import { createId } from '@/lib/types';
import type { QRProfile } from '@/lib/types';

export default function HistoryScreen() {
  const router = useRouter();
  const { colors, t, profiles, deleteProfile, toggleFavorite, upsertProfile, isRTL } = useApp();
  const remove = (profile: QRProfile) => Alert.alert(t('deleteConfirm'), profile.name, [{ text: t('cancel'), style: 'cancel' }, { text: t('delete'), style: 'destructive', onPress: () => deleteProfile(profile.id) }]);
  return <Screen><Eyebrow>{t('history')}</Eyebrow><PageTitle subtitle={t('historySubtitle')}>Your QR library.</PageTitle>
    {profiles.length === 0 ? <View style={[styles.empty, { backgroundColor: colors.card, borderColor: colors.border }]}><Feather name="archive" size={24} color={colors.mutedForeground} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>{t('noHistory')}</Text><Text style={[styles.emptyText, { color: colors.mutedForeground }]}>{t('historySubtitle')}</Text><Pressable onPress={() => router.push('/create')} style={[styles.primary, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground, fontWeight: '800' }}>{t('createQr')}</Text></Pressable></View> : profiles.map((profile) => <HistoryCard key={profile.id} profile={profile} colors={colors} isRTL={isRTL} t={t} onEdit={() => router.push({ pathname: '/create', params: { profileId: profile.id } })} onFavorite={() => toggleFavorite(profile.id)} onDelete={() => remove(profile)} onShare={() => void Share.share({ message: encodeProfile(profile), title: profile.name })} onDuplicate={() => { const copy = { ...profile, id: createId(), name: `${profile.name} copy`, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), fields: profile.fields.map((field) => ({ ...field, id: createId() })) }; upsertProfile(copy); router.push({ pathname: '/create', params: { profileId: copy.id } }); }} />)}
  </Screen>;
}

function HistoryCard({ profile, colors, isRTL, t, onEdit, onFavorite, onDelete, onShare, onDuplicate }: { profile: QRProfile; colors: any; isRTL: boolean; t: (key: any) => string; onEdit: () => void; onFavorite: () => void; onDelete: () => void; onShare: () => void; onDuplicate: () => void }) {
  return <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.cardTop, isRTL && styles.rtl]}><QrPreview profile={profile} size={88} /><View style={{ flex: 1, gap: 5 }}><Text style={[styles.name, { color: colors.foreground }]}>{profile.name}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{profile.fields.filter((field) => field.enabled && field.value).length} fields · {new Date(profile.updatedAt).toLocaleDateString()}</Text><View style={styles.pill}><Text style={[styles.pillText, { color: colors.accentForeground }]}>LOCAL ONLY</Text></View></View><Pressable onPress={onFavorite}><Feather name={profile.favorite ? 'star' : 'star'} size={20} color={profile.favorite ? colors.tint : colors.mutedForeground} /></Pressable></View><View style={[styles.actions, isRTL && styles.rtl]}><Pressable onPress={onEdit} style={[styles.action, { backgroundColor: colors.secondary }]}><Feather name="edit-2" size={14} color={colors.secondaryForeground} /><Text style={{ color: colors.secondaryForeground, fontSize: 12, fontWeight: '700' }}>{t('edit')}</Text></Pressable><Pressable onPress={onDuplicate} style={[styles.action, { backgroundColor: colors.secondary }]}><Feather name="copy" size={14} color={colors.secondaryForeground} /><Text style={{ color: colors.secondaryForeground, fontSize: 12, fontWeight: '700' }}>{t('duplicate')}</Text></Pressable><Pressable onPress={onShare} style={[styles.action, { backgroundColor: colors.accent }]}><Feather name="share-2" size={14} color={colors.accentForeground} /><Text style={{ color: colors.accentForeground, fontSize: 12, fontWeight: '700' }}>{t('share')}</Text></Pressable><Pressable onPress={onDelete} style={[styles.deleteAction, { backgroundColor: colors.secondary }]}><Feather name="trash-2" size={14} color={colors.destructive} /></Pressable></View></View>;
}

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 20, padding: 13, marginBottom: 11 }, cardTop: { flexDirection: 'row', alignItems: 'center', gap: 13 }, rtl: { flexDirection: 'row-reverse' }, name: { fontSize: 15, fontWeight: '800' }, meta: { fontSize: 12 }, pill: { alignSelf: 'flex-start', borderRadius: 7, paddingHorizontal: 7, paddingVertical: 4, backgroundColor: '#d7f5f2' }, pillText: { fontSize: 9, fontWeight: '800', letterSpacing: 0.7 }, actions: { flexDirection: 'row', gap: 6, marginTop: 13 }, action: { flex: 1, borderRadius: 10, paddingVertical: 9, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 5 }, deleteAction: { width: 35, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, empty: { borderWidth: 1, borderRadius: 20, padding: 26, alignItems: 'center', gap: 9 }, emptyTitle: { fontSize: 16, fontWeight: '800' }, emptyText: { textAlign: 'center', fontSize: 13, lineHeight: 19 }, primary: { borderRadius: 12, paddingHorizontal: 17, paddingVertical: 12, marginTop: 7 } });